name: Spellint Check

on:
  pull_request:
    branches: [main]

jobs:
  spellint:
    name: Run Spellint Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run Spellint via NPX
        run: npx spellint .
