name: Spellint Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  spellint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run Spellint with NPX
        run: npx spellint .
